
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import type { AppProps } from 'next/app'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
title: "Create Next App",
  description: "Generated by create next app",
};




const App =  ({
 children
}: React.PropsWithChildren
) => {



  return (
    <html>
      <body>
          {children}
      </body>
    </html>
  )

}

export default App